I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 667, in script
    el "..."
Exception: Sayer 'el' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 667, in script
    el "..."
  File "C:\Users\Sareel\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Sareel\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'el' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
TTW 1.0
Mon Jul 27 21:18:37 2020
